<html><head><meta charset="utf-8"></meta></head><body><h1 class="article-title" style="text-align:center;">JUnit4测试方法异常抛出实例</h1><div style="width:100%;float:left;" class="article-content">   
 <p> 它用于测试由方法抛出的异常。 </p> 
 <p> </p>
 <pre class="prettyprint lang-java">import org.junit.*;

/**
 * JUnit Expected Exception Test
 * @author yiibai
 *
 */
public class JunitTest2 {
   
	@Test(expected = ArithmeticException.class)  
	public void divisionWithException() {  
	  int i = 1/0;
	}  
    
}</pre> 
 <p></p> 
 <div> 
  <p> 在上述例子中，divisionWithException()方法将抛出ArithmeticException异常，因为这是一个预期的异常，因此单元测试会通过。 </p> 
  <div> 
   <br> 
  </div> 
 </div>
 <br>      
</div></body></html>