<html><head><meta charset="utf-8"></meta></head><body><h1 class="article-title" style="text-align:center;">C++ try/catch语句</h1><div style="width:100%;float:left;" class="article-content">   
 <p>在C++编程中，使用<code>try/catch</code>语句执行异常处理。 C++ <code>try</code>块用于放置可能发生异常的代码。<code>catch</code>块用于处理异常。</p> 
 <h2 id="h2--try-catch-"><a name="没有try/catch的示例" class="reference-link"></a><span class="header-link octicon octicon-link"></span>没有try/catch的示例</h2>
 <pre><code class="lang-cpp">#include &lt;iostream&gt;  
using namespace std;  
float division(int x, int y) {  
   return (x/y);  
}  
int main () {  
   int i = 50;  
   int j = 0;  
   float k = 0;  
      k = division(i, j);  
      cout &lt;&lt; k &lt;&lt; endl;  
   return 0;  
}
</code></pre> 
 <p>执行上面代码得到以下结果 -</p> 
 <pre><code class="lang-cpp">Floating point exception (core dumped)
</code></pre> 
 <h2 id="h2-c-try-catch-"><a name="C++ try/catch示例" class="reference-link"></a><span class="header-link octicon octicon-link"></span>C++ try/catch示例</h2>  
 <pre><code class="lang-cpp">#include &lt;iostream&gt;  
using namespace std;  
float division(int x, int y) {  
   if( y == 0 ) {  
      throw "Attempted to divide by zero!";  
   }  
   return (x/y);  
}  
int main () {  
   int i = 25;  
   int j = 0;  
   float k = 0;  
   try {  
      k = division(i, j);  
      cout &lt;&lt; k &lt;&lt; endl;  
   }catch (const char* e) {  
      cerr &lt;&lt; e &lt;&lt; endl;  
   }  
   return 0;  
}
</code></pre> 
 <p>执行上面代码，得到以下结果 -</p> 
 <pre><code class="lang-cpp">Attempted to divide by zero!
</code></pre>
 <br>      
</div></body></html>