<html><head><meta charset="utf-8"></meta></head><body><h1 class="article-title" style="text-align:center;">Go语言错误处理</h1><div style="width:100%;float:left;" class="article-content">   
 <p>Go编程提供了一个非常简单的错误处理框架，以及内置的错误接口类型，如下声明：</p> 
 <pre><code class="lang-go">type error interface {
   Error() string
}
</code></pre> 
 <p>函数通常返回错误作为最后一个返回值。 可使用<code>errors.New</code>来构造一个基本的错误消息，如下所示：</p> 
 <pre><code class="lang-go">func Sqrt(value float64)(float64, error) {
   if(value &lt; 0){
      return 0, errors.New("Math: negative number passed to Sqrt")
   }
   return math.Sqrt(value)
}
</code></pre> 
 <p>使用返回值和错误消息，如下所示 - </p> 
 <pre><code class="lang-go">result, err:= Sqrt(-1)

if err != nil {
   fmt.Println(err)
}
</code></pre> 
 <h3 id="h3-u793Au4F8B"><a name="示例" class="reference-link"></a><span class="header-link octicon octicon-link"></span>示例</h3>
 <pre><code class="lang-go">package main

import "errors"
import "fmt"
import "math"

func Sqrt(value float64)(float64, error) {
   if(value &lt; 0){
      return 0, errors.New("Math: negative number passed to Sqrt")
   }
   return math.Sqrt(value), nil
}

func main() {
   result, err:= Sqrt(-1)

   if err != nil {
      fmt.Println(err)
   }else {
      fmt.Println(result)
   }

   result, err = Sqrt(9)

   if err != nil {
      fmt.Println(err)
   }else {
      fmt.Println(result)
   }
}
</code></pre> 
 <p>当上述代码编译和执行时，它产生以下结果：</p>   
 <pre><code class="lang-go">Math: negative number passed to Sqrt
3
</code></pre>
 <br>      
</div></body></html>