<html><head><meta charset="utf-8"></meta></head><body><h1 class="article-title" style="text-align:center;">Java异常抛出</h1><div style="width:100%;float:left;" class="article-content">   
 <p>如果要在一段代码中抛出一个已检查的异常，有两个选择：</p> 
 <ul> 
  <li>使用<code>try-catch</code>块处理已检查的异常。</li>
  <li>在方法/构造函数声明中用<code>throws</code>子句指定。</li>
 </ul> 
 <h2 id="h2-u8BEDu6CD5"><a name="语法" class="reference-link"></a><span class="header-link octicon octicon-link"></span>语法</h2>
 <p><code>throws</code>子句的一般语法是：</p> 
 <pre><code class="lang-java">&lt;modifiers&gt; &lt;return type&gt; &lt;method name&gt;(&lt;params&gt;) throws&lt;List of Exceptions&gt;{

}
</code></pre> 
 <p>关键字<code>throws</code>用于指定<code>throws</code>子句。<code>throws</code>子句放在方法参数列表的右括号之后。<code>throws</code>关键字后面是以逗号分隔异常类型的列表。</p> 
 <h2 id="h2--1"><a name="示例-1" class="reference-link"></a><span class="header-link octicon octicon-link"></span>示例-1</h2>
 <p>以下代码显示如何在方法声明中使用<code>throws</code>子句</p> 
 <pre><code class="lang-java">import java.io.IOException;

public class Main {
  public static void readChar() throws IOException {
    int input = System.in.read();

  }
}
</code></pre> 
 <p>这里是显示如何使用它的代码。</p> 
 <h2 id="h2--2"><a name="实例-2" class="reference-link"></a><span class="header-link octicon octicon-link"></span>实例-2</h2>
 <p>在调用方法中捕捉抛出的异常 - </p> 
 <pre><code class="lang-java">import java.io.IOException;

public class Main {
  public static void readChar() throws IOException {
    int input = System.in.read();
    System.out.println(input);
  }

  public static void main(String[] args) {
    try {
      readChar();
    } catch (IOException e) {
      System.out.println("Error occurred.");
    }
  }

}
</code></pre> 
 <p>上面的代码生成以下结果(输入<code>-1</code>回车，得到以下结果)。</p> 
 <pre><code class="lang-java">-1
45
</code></pre> 
 <h2 id="h2--3"><a name="实例-3" class="reference-link"></a><span class="header-link octicon octicon-link"></span>实例-3</h2>
 <p>继续 <strong>实例-2</strong> 直接抛出异常。</p> 
 <pre><code class="lang-java">import java.io.IOException;

public class Main {
  public static void readChar() throws IOException {
    int input = System.in.read();
    System.out.println(input);
  }

  public static void main(String[] args) throws IOException {
    readChar();
  }
}
</code></pre> 
 <p>上面的代码生成以下结果(输入<code>-1</code>回车，得到以下结果)。</p>   
 <pre><code class="lang-java">-1
45
</code></pre> 
 <h2 id="h2-u629Bu51FAu5F02u5E38"><a name="抛出异常" class="reference-link"></a><span class="header-link octicon octicon-link"></span>抛出异常</h2>
 <p>可以使用<code>throw</code>语句在代码中抛出异常。<code>throw</code>语法的语法是 - </p> 
 <pre><code class="lang-java">throw &lt;A throwable object reference&gt;;
</code></pre> 
 <p><code>throw</code>是一个关键字，后面跟着一个可抛出对象的引用。<code>throwable</code>对象是一个类的实例，它是<code>Throwable</code>类的子类，或<code>Throwable</code>类本身。</p> 
 <p>以下是<code>throw</code>语句的示例，它抛出一个<code>IOException</code>：</p> 
 <pre><code class="lang-java">// Create an  object of  IOException
IOException e1  = new IOException("File not  found");
// Throw the   IOException 
throw  e1;
</code></pre> 
 <p>可以创建一个<code>throwable</code>对象并将其放在一个语句中。</p> 
 <pre><code class="lang-java">// Throw an  IOException
throw  new IOException("File not  found");
</code></pre> 
 <p>如果抛出一个被检查的异常，必须使用<code>try-catch</code>块来处理它，或者在方法或构造函数声明中使用<code>throws</code>子句。</p> 
 <p>如果抛出未经检查的异常，上面的这些规则不适用。</p>
 <br>      
</div></body></html>