<html><head><meta charset="utf-8"></meta></head><body><h1 class="article-title" style="text-align:center;">Scala finally块</h1><div style="width:100%;float:left;" class="article-content">   
 <p><code>finally</code>块用于在异常时释放资源。资源可能是文件，网络连接，数据库连接等，<code>finally</code>块执行代码运行保证。以下程序说明了<code>finally</code>块的用法。</p> 
 <p><strong>Scala finally块示例</strong></p> 
 <pre><code class="lang-scala">class ExceptionExample{  
    def divide(a:Int, b:Int) = {  
        try{  
            a/b  
            var arr = Array(1,2)  
            arr(10)  
        }catch{  
            case e: ArithmeticException =&gt; println(e)  
            case ex: Exception =&gt;println(ex)  
            case th: Throwable=&gt;println("found a unknown exception"+th)  
        }  
        finally{  
            println("Finaly block always executes")  
        }  
        println("Rest of the code is executing...")  
    }  
}  


object Demo{  
    def main(args:Array[String]){  
        var e = new ExceptionExample()  
        e.divide(100,10)  

    }  
}
</code></pre> 
 <p>将上面代码保存到源文件：<em>Demo.scala</em>中，使用以下命令编译并执行代码 - </p>   
 <pre><code class="lang-shell">D:\software\scala-2.12.3\bin&gt;scalac Demo.scala
D:\software\scala-2.12.3\bin&gt;scala Demo.scal
java.lang.ArrayIndexOutOfBoundsException: 10
Finally block always executes
Rest of the code is executing...
</code></pre>
 <br>      
</div></body></html>